server:
  port: 8087
spring:
  security:
    enabled: false
app:
  nic: w-sumie-nic-mi-sie-nie-udaje-1-i-dupa-123-coa

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, refresh
        # include: info, health, refresh
