server:
  port: 8087
spring:
  security:
    enabled: false
app:
  nic: w-sumie-nic-mi-sie-nie-udaje-1-i-dupa

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: info, health, loggers, metrics, prometheus, liquibase, refresh
