server:
  port: 8087
spring:
  security:
    enabled: false
app:
  nic: ciekawe-

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, refresh
        # include: info, health, refresh
